name: Auto Checkin

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  Coordinated Universal Time (UTC)
  schedule:
    - cron: '0 23 * * *'
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    # 只有自己点 Star 才触发
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Python Setup
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    # 缓存 pip 模块
    - name: Pip Cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: ${{ runner.os }}-pip-
    # 缓存历史记录于 ~/.cache/actions.log
    - name: Log Cache
      uses: actions/cache@v2
      with:
        path: ~/.cache
        key: ${{ runner.os }}-log-${{ hashFiles('**/actions.log') }}
        restore-keys: ${{ runner.os }}-log-
    - name: Addons Install
      run: pip install lxml requests
    # 获取机密并写入临时文件和脚本
    - name: Secrets Get
      env: 
        SECRET_ID: ${{ secrets.SECRET_ID }}
        SECRET_PASS: ${{ secrets.SECRET_PASS }}
        SECRET_BOUND: ${{ secrets.SECRET_BOUND }}
        SECRET_DATA: ${{ secrets.SECRET_DATA }}
      run: | 
        cp checkin.py action.py
        echo $SECRET_ID > action-id.txt
        echo $SECRET_PASS > action-pass.txt
        echo $SECRET_BOUND > action-bound.txt
        echo $SECRET_DATA > action-data.txt
        sed -i '19 r action-id.txt' action.py
        sed -i '20 r action-pass.txt' action.py
        sed -i '21 r action-bound.txt' action.py
        sed -i '22 r action-data.txt' action.py
    # 执行签到前复制缓存的 actions.log 并将此次签到记录写入文件后面
    - name: Checkin Action
      env:
        TZ: Asia/Shanghai
      run: | 
        mkdir log
        if [ -f "~/.cache/actions.log" ] ; then cp ~/.cache/actions.log log/actions.log ; fi
        echo "============================" >> log/actions.log && echo `date +"%Y-%m-%d %H:%M:%S %A"` >> log/actions.log
        python action.py >> log/actions.log && echo >> log/actions.log
        cp log/actions.log ~/.cache/actions.log
    # 删除机密
    - name: Secrets Delete
      run: rm -f action*
    # 发布 log 文件夹下历史记录文件到 log 分支
    - name: Deploy Log
      uses: docker://peaceiris/gh-pages:v2
      env:
        TZ: Asia/Shanghai
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: log
        PUBLISH_DIR: ./log
      with:
        emptyCommits: false