name: 作者自用 Ruby 打卡

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  self-checkin-ruby:
    runs-on: ubuntu-latest
    services:
      hub:
        image: selenium/hub:3.141.59-gold
        env:
          SELENIUM_HUB_HOST: localhost
      chrome:
        image: selenium/node-chrome:3.141.59-gold
        env:
          HUB_HOST: localhost
          HUB_PORT: 9515
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Setup
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.5.x
    - name: Cache
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: ${{ runner.os }}-gems-
    - name: Install
      run: gem install watir headless webdrivers
    - name: Execute
      env:
        TZ: Asia/Shanghai
        LANG: zh_CN.UTF-8
        SECRET_ID: ${{ secrets.SECRET_ID }}
        SECRET_PASS: ${{ secrets.SECRET_PASS }}
        SECRET_SCKEY: ${{ secrets.SECRET_SCKEY }}
      run: |
        # ruby Actions/checkin.rb | tee -a Logs/checkin-ruby.log
        curl -d "text=打卡状态&desp=$(echo && echo ' - 签到账号：'$(echo $SECRET_ID) \
          && echo && echo ' - 签到时间：'$(date +"%Y-%m-%d %H:%M:%S %A") \
          && echo && echo ' - 运行记录：run.log' \
          && echo && echo '--------------' \
          && echo && echo '`run.log`' \
          && echo && echo '```' && ruby Self/checkin.rb | tee -a Self/checkin-ruby.log \
          && echo && echo '```' && echo)" \
          $(echo 'https://sc.ftqq.com/'$SECRET_SCKEY'.send')
        (echo "[info] Log Sent at "$(date +"%Y-%m-%d %H:%M:%S %A") && echo '=========================' && echo) | tee -a Self/checkin-ruby.log
    - name: Commit
      env:
        TZ: Asia/Shanghai
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git pull
        git add Self/checkin-ruby.log
        git commit -m \
          "Update ruby log at \
          $(date +"%Y-%m-%d %H:%M") \
          "
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}