name: Ruby 打卡

on:
  # 两个工作流同时开启时等待 Python 完成提交后再开始
  # 否则由于仓库变动会导致 log 文件提交失败
  # workflow_run:
  #   workflows: ["Python 打卡"]
  #   types: 
  #     - completed
  #
  schedule:
    - cron: "30 0,23 * * *"
  workflow_dispatch:

jobs:
  checkin-ruby:
    runs-on: ubuntu-latest
    services:
      hub:
        image: selenium/hub:3.141.59-gold
        env:
          SELENIUM_HUB_HOST: localhost
      chrome:
        image: selenium/node-chrome:3.141.59-gold
        env:
          HUB_HOST: localhost
          HUB_PORT: 9515
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Setup
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.5.x
    - name: Cache
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: ${{ runner.os }}-gems-
    - name: Install
      run: gem install watir headless webdrivers
    - name: Execute
      env:
        TZ: Asia/Shanghai
        LANG: zh_CN.UTF-8
        SECRET_ID: ${{ secrets.SECRET_ID }}
        SECRET_PASS: ${{ secrets.SECRET_PASS }}
        SECRET_SCKEY: ${{ secrets.SECRET_SCKEY }}
      run: |
        # ruby Actions/checkin.rb | tee -a Logs/checkin-ruby.log
        ruby Actions/checkin.rb | tee tmp | tee -a Logs/checkin-ruby.log
        curl -d "text=${SECRET_ID}$(if [[ $(tail -n 3 tmp) =~ "Success" ]] then echo "打卡成功"; else echo "打卡失败"; fi)\
        &desp=$(echo '运行日志：checkin-ruby.log' && echo && echo '---' && echo && echo '```' && cat tmp && echo '```')" \
        https://sc.ftqq.com/${SECRET_SCKEY}.send
        echo "[info] Log Sent at "$(date +"%Y-%m-%d %H:%M:%S %A") >> Logs/checkin-ruby.log
        echo '=========================\n' >> Logs/checkin-ruby.log && rm tmp
    - name: Commit
      env:
        TZ: Asia/Shanghai
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git pull
        git add Logs/checkin-ruby.log
        git commit -m \
          "Update ruby log at \
          $(date +"%Y-%m-%d %H:%M") \
          "
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}